<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        /* Base Reset */
        body {
            font-family: 'Courier New', Courier, monospace;
            font-family: system-ui, -apple-system, sans-serif;
            background-color: #f3f4f6;
            color: #131011;
            margin: 0;
            padding: 40px 20px;
        }

        /* Brutalist Container */
        .email-wrapper {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border: 4px solid #131011;
            box-shadow: 10px 10px 0px 0px #0095AC;
            padding: 0;
        }

        /* Dark Header with Logo */
        .header {
            background-color: #131011;
            padding: 30px 20px;
            text-align: center;
            border-bottom: 4px solid #131011;
        }

        .header img {
            max-width: 250px;
            height: auto;
            display: block;
            margin: 0 auto;
        }

        /* Body Content */
        .content {
            padding: 40px 30px;
            font-size: 16px;
            line-height: 1.6;
            background-color: #FFFBF7;
        }

        h2 {
            color: #0095AC;
            text-transform: uppercase;
            margin-top: 0;
            border-bottom: 4px solid #0095AC;
            display: inline-block;
            padding-bottom: 5px;
            letter-spacing: 1px;
            font-size: 24px;
        }

        /* Stylized Team Tag */
        .team-name {
            background-color: #FF8623;
            color: #131011;
            font-weight: bold;
            padding: 2px 8px;
            border: 2px solid #131011;
            text-transform: uppercase;
        }

        /* Brutalist Alert Box */
        .status-box {
            background-color: #ffffff;
            border: 4px solid #131011;
            padding: 20px;
            margin: 30px 0;
            box-shadow: 6px 6px 0px 0px #10B981;
        }

        .status-title {
            font-weight: bold;
            text-transform: uppercase;
            color: #10B981;
            margin-bottom: 10px;
            font-size: 14px;
            letter-spacing: 1px;
        }

        .credentials-block {
            background-color: #f3f4f6;
            border: 2px dashed #131011;
            padding: 15px;
            margin-top: 15px;
        }

        /* Footer */
        .footer {
            background-color: #e5e7eb;
            border-top: 4px solid #131011;
            padding: 20px;
            font-size: 12px;
            text-align: center;
            color: #4b5563;
        }

        .important-text {
            font-weight: bold;
            color: #CF452C;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <div class="email-wrapper">

        <!-- Header with Embedded Logo -->
        <div class="header">
            <img src="{{ $message->embed(public_path('images/HOI Logo Blue.png')) }}" alt="Heroes of Innovation Challenge 2026">
        </div>

        <div class="content">
            <h2>Transmission Received!</h2>

            <p>Hi <strong>{{ $leaderName }}</strong>,</p>

            <p>Congratulations! <span class="team-name">{{ $teamName }}</span> has been officially verified and approved for the Heroes of Innovation Challenge 2026.</p>

            <!-- Brutalist Status Box -->
            <div class="status-box">
                <div class="status-title">▶ SYSTEM STATUS: ACCESS GRANTED</div>
                <p style="margin: 0;">Below are your official keys to the Community Center mainframe. Please keep these secure.</p>

                <div class="credentials-block">
                    <p style="margin: 0 0 5px 0; font-size: 12px; color: #4b5563; text-transform: uppercase;">Portal Login Details</p>
                    <p style="margin: 0 0 5px 0;"><strong>URL:</strong> <a href="{{ route('ibalong.login') }}" style="color: #0095AC;">{{ route('ibalong.login') }}</a></p>
                    <p style="margin: 0 0 5px 0;"><strong>Email:</strong> {{ $email }}</p>
                    <p style="margin: 0;"><strong>Password:</strong> {{ $password }}</p>
                </div>
            </div>

            <p><span class="important-text">Your First Directive:</span><br>
            Log into the portal immediately, head to your Dashboard, and complete your team profile by uploading your official Team Logo and Member Photos.</p>

            <p>We look forward to seeing what you build!</p>

            <br>
            <p>Best regards,<br><strong>Heroes of Innovation 2026 Organizing Committee</strong></p>
        </div>

        <!-- Footer -->
        <div class="footer">
            <p style="margin: 0 0 10px 0;"><strong>SYSTEM ALERT:</strong> This is an automated message generated by the Community Center mainframe. Please do not reply directly to this email.</p>
            <p style="margin: 0; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; color: #9ca3af;">Powered by BU MADYA Web | Heroes of Innovation 2026</p>
        </div>

    </div>
</body>
</html>
